scheme: pcqm4mv2
model_name: egt_90m
distributed: false         # 设置为true启用多GPU分布式训练
batch_size: 512             # 单GPU时的批次大小;多GPU时需调整为总批次大小除以GPU数量
model_height: 24
node_width: 768
edge_width: 64
num_heads: 32
num_epochs: 1
max_lr: 0.0001
attn_dropout: 0.3
lr_warmup_steps: 200000
lr_total_steps: 1000000
node_ffn_multiplier: 1.0
edge_ffn_multiplier: 1.0
upto_hop: 16
dataloader_workers: 1       # 多线程数
scale_degree: true
num_virtual_nodes: 4
svd_random_neg: true
mixed_precision: true       # 启用混合精度
use_adaptive_sparse: true   # 启用自适应稀疏
sparse_alpha: 0.5           # 稀疏化强度系数
