inj_cora:
  lr: 0.001
  lr_f: 0.001
  num_heads: 1
  weight_decay: 2e-4
  max_epoch: 20
  max_epoch_f: 20
  num_layers: 2
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  optimizer: adam
  alpha_l: 3
  scheduler: True
  mask_rate1: 0.01
  drop_edge_rate1: 0
  drop_path_rate1: 0
  drop_path_length1: 3
  mask_rate2: 0
  drop_edge_rate2: 0.01
  drop_path_rate2: 0.01
  drop_path_length2: 3
  attr_pretrain_uncertainty_rate: 0
  struct_pretrain_uncertainty_rate: 0
  attr_remask_uncertainty_rate: 0
  struct_remask_uncertainty_rate: 0
  max_pu_epoch: 45
  each_pu_epoch: 15
  dropout_f: 0
  attr_encoder: "gcn"
  struct_encoder: "gcn"
  topology_encoder: "gcn"
  attr_decoder: "gcn"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  edge_encoder_num_layers: 1
  subgraph_encoder_num_layers: 1
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 32
  predict_all_edge2: 0
  predict_all_edge3: 0
  loss_weight_f: 0
  alpha_f: "None"
  replace_rate: 0
  # Configuration Added Below
  model_name: "ADANET"
  loss_f: "add_log_t_entropy"
  attention: 2
  T_f: 2
  use_encoder_num: 3
  predict_all_edge2: 0
  predict_all_edge3: 0
  loss_weight_f: 0
  mask_rate1: 0.01
  drop_edge_rate2: 0.01
  drop_path_rate3: 0.01
  alpha_f: None
  replace_rate: 0
  num_hidden: 60
inj_amazon:
  lr: 0.001
  lr_f: 0.01
  num_heads: 1
  weight_decay: 2e-4
  max_epoch: 20
  max_epoch_f: 20
  num_layers: 2
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  optimizer: adam
  alpha_l: 3
  scheduler: True
  mask_rate1: 0.01
  drop_edge_rate1: 0
  drop_path_rate1: 0
  drop_path_length1: 3
  predict_all_node1: False
  mask_rate2: 0
  drop_edge_rate2: 0.01
  drop_path_rate2: 0.01
  predict_all_node2: False
  drop_path_length2: 3
  attr_pretrain_uncertainty_rate: 0
  struct_pretrain_uncertainty_rate: 0
  attr_remask_uncertainty_rate: 0
  struct_remask_uncertainty_rate: 0
  max_pu_epoch: 45
  each_pu_epoch: 15
  dropout_f: 0
  attr_encoder: "gcn"
  struct_encoder: "gcn"
  topology_encoder: "gcn"
  attr_decoder: "gcn"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  edge_encoder_num_layers: 1
  subgraph_encoder_num_layers: 1
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 32
  predict_all_edge2: 0
  predict_all_edge3: 0.05
  loss_weight_f: -0.01
  alpha_f: "None"
  replace_rate: 0.4
  # Configuration Added Below for inj_amazon
  model_name: "ADANET"
  loss_f: "add_log_t_entropy"
  attention: 2
  T_f: 2
  use_encoder_num: 3
  predict_all_edge3: 0.05
weibo:
  lr: 0.001
  lr_f: 0.01
  num_heads: 1
  weight_decay: 2e-4
  max_epoch: 20
  max_epoch_f: 20
  num_layers: 2
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  optimizer: adam
  alpha_l: 3
  scheduler: True
  mask_rate1: 0.01
  drop_edge_rate1: 0
  drop_path_rate1: 0
  drop_path_length1: 3
  predict_all_node1: False
  mask_rate2: 0
  predict_all_node2: False
  drop_path_length2: 3
  attr_pretrain_uncertainty_rate: 0
  struct_pretrain_uncertainty_rate: 0
  attr_remask_uncertainty_rate: 0
  struct_remask_uncertainty_rate: 0
  max_pu_epoch: 45
  each_pu_epoch: 15
  dropout_f: 0
  attr_encoder: "gat"
  struct_encoder: "gat"
  topology_encoder: "gat"
  attr_decoder: "gcn"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  edge_encoder_num_layers: 1
  subgraph_encoder_num_layers: 1
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 48
  predict_all_edge2: 0
  predict_all_edge3: 0.1
  loss_weight_f: -0.001
  alpha_f: 0.9938
  replace_rate: 0.5
  # Configuration Added Below for weibo
  model_name: "ADANET"
  loss_f: "add_log_t_entropy"
  attention: 2
  T_f: 2
  use_encoder_num: 3
  predict_all_edge2: 0
  predict_all_edge3: 0.1
  loss_weight_f: -0.1
  mask_rate1: 0.01
  drop_edge_rate2: 0.01
  drop_path_rate3: 0.01
  alpha_f: None
  replace_rate: 0.8
reddit:
  lr: 0.001
  lr_f: 0.001
  num_heads: 1
  weight_decay: 2e-4
  max_epoch: 20
  max_epoch_f: 20
  num_layers: 2
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  optimizer: adam
  alpha_l: 3
  scheduler: True
  mask_rate1: 0.01
  drop_edge_rate1: 0
  drop_path_rate1: 0
  drop_path_length1: 3
  predict_all_node1: False
  mask_rate2: 0
  predict_all_node2: False
  drop_path_length2: 3
  attr_pretrain_uncertainty_rate: 0
  struct_pretrain_uncertainty_rate: 0
  attr_remask_uncertainty_rate: 0
  struct_remask_uncertainty_rate: 0
  max_pu_epoch: 45
  each_pu_epoch: 15
  dropout_f: 0
  attr_encoder: "gcn"
  struct_encoder: "gcn"
  topology_encoder: "gcn"
  attr_decoder: "gcn"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  edge_encoder_num_layers: 1
  subgraph_encoder_num_layers: 1
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 32
  predict_all_edge2: 0
  predict_all_edge3: 0
  loss_weight_f: -0.01
  alpha_f: 0.5
  replace_rate: 0
  # Configuration Added Below for reddit
  model_name: "ADANET"
  loss_f: "add_log_t_entropy"
  attention: 2
  T_f: 2
  use_encoder_num: 3
  predict_all_edge2: 0.1
  predict_all_edge3: 0
  loss_weight_f: -1
  mask_rate1: 0.01
  drop_edge_rate2: 0.01
  drop_path_rate3: 0.01
  alpha_f: 0.9
  replace_rate: 0.5
disney:
  lr: 0.001
  lr_f: 0.01
  num_heads: 1
  weight_decay: 2e-4
  max_epoch: 20
  max_epoch_f: 20
  num_layers: 2
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  optimizer: adam
  alpha_l: 3
  scheduler: True
  mask_rate1: 0.01
  drop_edge_rate1: 0
  drop_path_rate1: 0
  drop_path_length1: 3
  mask_rate2: 0
  drop_edge_rate2: 0.01
  drop_path_rate2: 0.01
  drop_path_length2: 3
  attr_pretrain_uncertainty_rate: 0
  struct_pretrain_uncertainty_rate: 0
  attr_remask_uncertainty_rate: 0
  struct_remask_uncertainty_rate: 0
  max_pu_epoch: 45
  each_pu_epoch: 15
  dropout_f: 0
  aggr_f: "min"
  attr_encoder: "gcn"
  struct_encoder: "gcn"
  topology_encoder: "gcn"
  attr_decoder: "gcn"
  struct_decoder: "gcn"
  node_encoder_num_layers: 2
  edge_encoder_num_layers: 2
  subgraph_encoder_num_layers: 2
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 8
  predict_all_edge2: 0.1
  predict_all_edge3: 0.1
  loss_weight_f: -0.01
  alpha_f: 0.9
  replace_rate: 0.3
  # Configuration Added Below for disney
  model_name: "ADANET"
  loss_f: "add_log_t_entropy"
  attention: 2
  T_f: 2
  use_encoder_num: 3
  predict_all_edge2: 0
  predict_all_edge3: 0
  loss_weight_f: -0.01
  mask_rate1: 0.01
  drop_edge_rate2: 0.01
  drop_path_rate3: 0.01
  alpha_f: 0.7
  replace_rate: 0
books:
  lr: 0.001
  lr_f: 0.01
  num_heads: 1
  weight_decay: 2e-4
  max_epoch: 20
  max_epoch_f: 20
  num_layers: 2
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  optimizer: adam
  alpha_l: 3
  scheduler: True
  mask_rate1: 0.01
  drop_edge_rate1: 0
  drop_path_rate1: 0
  drop_path_length1: 3
  mask_rate2: 0
  drop_edge_rate2: 0.01
  drop_path_rate2: 0.01
  drop_path_length2: 3
  attr_pretrain_uncertainty_rate: 0
  struct_pretrain_uncertainty_rate: 0
  attr_remask_uncertainty_rate: 0
  struct_remask_uncertainty_rate: 0
  max_pu_epoch: 45
  each_pu_epoch: 15
  dropout_f: 0
  aggr_f: "min"
  attr_encoder: "gcn"
  struct_encoder: "gcn"
  topology_encoder: "gcn"
  attr_decoder: "gcn"
  struct_decoder: "gcn"
  node_encoder_num_layers: 2
  edge_encoder_num_layers: 2
  subgraph_encoder_num_layers: 2
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 12
  predict_all_edge2: 0
  predict_all_edge3: 0
  loss_weight_f: -0.01
  alpha_f: 0.7
  replace_rate: 0
  # Configuration Added Below for books
  model_name: "ADANET"
  loss_f: "add_log_t_entropy"
  attention: 2
  T_f: 2
  use_encoder_num: 3
  predict_all_edge2: 0.1
  predict_all_edge3: 0.1
  loss_weight_f: -1
  mask_rate1: 0.01
  drop_edge_rate2: 0.01
  drop_path_rate3: 0.01
  alpha_f: 0.9
  replace_rate: 0.3
enron:
  lr: 0.001
  lr_f: 0.001
  num_heads: 1
  weight_decay: 2e-4
  max_epoch: 20
  max_epoch_f: 20
  num_layers: 2
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  optimizer: adam
  alpha_l: 3
  scheduler: True
  mask_rate1: 0.01
  drop_edge_rate1: 0
  drop_path_rate1: 0
  drop_path_length1: 3
  mask_rate2: 0
  drop_edge_rate2: 0.01
  drop_path_rate2: 0.01
  drop_path_length2: 3
  attr_pretrain_uncertainty_rate: 0
  struct_pretrain_uncertainty_rate: 0
  attr_remask_uncertainty_rate: 0
  struct_remask_uncertainty_rate: 0
  max_pu_epoch: 45
  each_pu_epoch: 15
  dropout_f: 0
  attr_encoder: "gat"
  struct_encoder: "gat"
  topology_encoder: "gat"
  attr_decoder: "gcn"
  struct_decoder: "gcn"
  node_encoder_num_layers: 2
  edge_encoder_num_layers: 2
  subgraph_encoder_num_layers: 2
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 32
  predict_all_edge2: 0.1
  predict_all_edge3: 0.1
  loss_weight_f: -0.001
  alpha_f: 0.7
  replace_rate: 0
  # Configuration Added Below for enron
  model_name: "ADANET"
  loss_f: "add_log_t_entropy"
  attention: 2
  T_f: 2
  use_encoder_num: 3
  predict_all_edge2: 0.1
  predict_all_edge3: 0.1
  loss_weight_f: 0
  mask_rate1: 0.01
  drop_edge_rate2: 0.01
  drop_path_rate3: 0.01
  alpha_f: 0.7
  replace_rate: 0
  num_hidden: 32
