name: Test Build Package

on: [workflow_dispatch]

jobs:
  build-package:
    runs-on: ubuntu-latest
    services:
      docker:
        image: quay.io/pypa/manylinux2010_x86_64
        options: --entrypoint /bin/bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .circleci/requirements.txt

      - name: Install TensorLayerx
        run: |
          pip install git+https://github.com/dddg617/TensorLayerX.git@nightly

      - name: Install PyTorch, torchvision and torchaudio
        run: |
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

      - name: Install llvmlite
        run: |
          pip install llvmlite

      - name: Install package
        run: |
          pip install gammagl
